visualization:
  visdom: True
  visdom_port: "8900"

data:
  name: "drums"
  root: "/home/brozserver2/brozdisk/data/nerf/nerf_synthetic/drums"
  type: "blender"
  white_bkgd: True
  reduce_res: 0.

model:
  netDepth: 8
  netWidth: 256

render:
  depth_near: 2.
  depth_far: 6.
  n_rays_per_image: 4096
  n_coarse_pts_per_ray: 64
  n_fine_pts_per_ray: 128
  chunk_ray: 4096
  chunk_pts: 65536

training:
  name: "drums_0730_1"
  start_iter: 0
  N_iters: 200000
  lr: 5e-4
  idx_print: 1000
  idx_save: 50000
  idx_test: 50000
  idx_video: 50000
  idx_visdom: 100

testing:
  name: "drums_0730_1"
  test_iter: 200000
  mode_test : True
  mode_render : False
  n_angle: 120
  single_angle : -1
  phi: -30.0
  testskip: 1
  