visualization:
  visdom: True
  visdom_port: "8900"

data:
  name: "lego"
  root: "/home/brozserver2/brozdisk/data/nerf/nerf_synthetic/lego"
  root_local: "/home/brozserver2/dev/NeRF_paeng/data/nerf_synthetic/lego"
  type: "blender"
  half_res: False
  white_bkgd: True

model:
  netDepth: 8
  netWidth: 256

render:
  depth_near: 2.
  depth_far: 6.
  n_rays_per_image: 1024
  n_coarse_pts_per_ray: 512
  n_fine_pts_per_ray: 128
  chunk_ray: 4096
  chunk_pts: 65536

training:
  name: "lego_0725_1"
  start_iter: 0
  N_iters: 200000
  lr: 5e-4
  idx_print: 1000
  idx_save: 50000
  idx_test: 50000
  idx_video: 50000
  idx_visdom: 100

testing:
  name: "lego_0725_1"
  test_iter: 250000
  mode_test : True
  mode_render : True
  n_angle: 40
  single_angle : -1
  phi: -30.0
  testskip: 1
  