visdom:
  use: False
  port: "8900"
  step: 100

data:
  name: "lego"
  root: "/home/brozserver2/dev/NeRF_paeng/data/nerf_synthetic/lego"
  type: "blender"
  half_res: False
  white_bkgd: True

training:
  batch_size: 2
  epoch: 300
  lr: 1e-4

model:
  netDepth: 8
  netWidth: 256
