visdom: False # Use Visdom or Not
visdom_port: "8900"
visdom_step: 100

training:
  batch_size: 2
  epoch: 300
  lr: 1e-4

data:
  name: "lego"
  root: "/home/brozserver2/dev/NeRF_paeng/data/nerf_synthetic/lego"
  type: "blender"
  half_res: False
  white_bkgd: True
