visualization:
  visdom: True
  visdom_port: "8900"

device:
  gpu_ids:
    - 0
  rank: 0

data:
  name: "lego"
  root: "/home/brozserver2/brozdisk/data/nerf/nerf_synthetic/lego"
  root_p: "/home/brozserver2/brozdisk/data/nerf/nerf_synthetic/lego"
  root_sm: 'C:\Users\csm81\Desktop\nerf\nerf_pytorch_\data\nerf_synthetic\lego'
  type: "blender"
  white_bkgd: True
  reduce_res: 0.

model:
  netDepth: 8
  netWidth: 256

render:
  depth_near: 2.
  depth_far: 6.
  n_rays_per_image: 4096
  n_coarse_pts_per_ray: 64
  n_fine_pts_per_ray: 128
  chunk_ray: 4096
  chunk_pts: 65536

training:
  name: "0801_2_lego"
  start_iter: 0
  N_iters: 200000
  lr: 5e-4
  idx_print: 1000
  idx_save: 50000
  idx_test: 50000
  idx_video: 100000
  idx_visdom: 100

testing:
  name: "0801_2_lego"
  test_iter: 50000
  mode_test : True
  mode_render : True
  n_angle: 40
  single_angle : -1
  phi: -30.0
  testskip: 8
  