visualization:
  visdom: True
  visdom_port: "8900"

device:
  gpu_ids:
    - 0
    - 1
  rank: 1

data:
  name: "mic"
  root: "[root]/mic"
  type: "blender"
  white_bkgd: True
  reduce_res: 0.

model:
  netDepth: 8
  netWidth: 256

render:
  depth_near: 2.
  depth_far: 6.
  n_rays_per_image: 4096
  n_coarse_pts_per_ray: 256
  n_fine_pts_per_ray: 0
  chunk_ray: 4096
  chunk_pts: 65536

training:
  name: "train_mic"
  start_iter: 0
  N_iters: 300000
  warmup_iter: 10000
  lr: 5e-4
  lr_min: 5e-5

  idx_print: 1000
  idx_save: 50000
  idx_test: 50000
  idx_render: 50000
  idx_visdom: 100

  precrop_iters: 500
  precrop_frac: .5

testing:
  name: "train_mic"
  test_iter: 2000000
  mode_test: True
  mode_render: True
  n_angle: 120
  single_angle: -1
  phi: -30.0
  testskip: 1
